temporal:
  service-address: ${TEMPORAL_SERVICE_ADDRESS:localhost:7233}
  namespace: ${TEMPORAL_NAMESPACE:default}
  cert-path: ${TEMPORAL_CERT_PATH:}
  key-path: ${TEMPORAL_KEY_PATH:}

spring:
  application:
    name: temporal-java-template
